### PR TITLE
20.Slide43-44

### PR DESCRIPTION
**Pull request by Almonarx**
Please check my homework

### CODE REVIEW

**Review by iliatcymbal — COMMENTED** [review]
I've got an error 

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/header/navigation/navigation.scss
    Module build failed: Error: Cannot find module 'node-sass'
```

Please, add missed module to package.json

**Comment by Almonarx** [comment]
screenshot-2017-11-20 almonarx tarasshevchenko-todo
I have this module

**Comment by iliatcymbal** [comment]
There are errors while building project

image

**Comment by iliatcymbal** [comment]
```
switch (true) {
        case props.hasOwnProperty('odd'):
            for (let i = +props.from; i <= +props.to; i++) {
                if (i % 2) arr.push(i);
            }
            break;

        case props.hasOwnProperty('even'):
            for (let i = +props.from; i <= +props.to; i++) {
                if (!(i % 2)) arr.push(i);
            }
            break;

        default:
            for (let i = +props.from; i <= +props.to; i++) {
                arr.push(i);
            }
            break;
    }
```
It is better not to use in this case switch operator. You can use _if... esle_ or _... ? ... :_ operator. 
And do not do three times the same operation (for statement has the same condition)

**Review by iliatcymbal — APPROVED** [review]
Looks good to me

**Pull request closed without merging**
